# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run the Unit test"
  lane :tests do
  run_tests(workspace: 'Surveys.xcworkspace',
            device: 'iPhone 12 Pro Max',
            scheme: 'SurveysTests',
	    buildlog_path: './fastlane/fastlane-buildlog',
 	    derived_data_path: '~/Library/Developer/Xcode/DerivedData',
	    ensure_devices_found: true,
	    open_report: true)
  end
end
